import { useSearchParams } from 'react-router';
import Game from '@/components/Game/Game';
import { useState } from 'react';
import { randomNo } from '@/utils/random';

const WordMap: Record<number, string[]> = {
  3: [
    'cat',
    'dog',
    'sun',
    'map',
    'car',
    'pen',
    'rat',
    'boy',
    'day',
    'lay',
    'try',
    'man',
    'bad',
    'bus',
    'cup',
    'fox',
    'god',
    'lab',
    'mad',
    'net',
    'pad',
    'pet',
    'run',
    'sat',
    'tab',
    'tap',
    'van',
    'was',
    'zip',
    'egg',
  ],
  4: [
    'able',
    'bite',
    'code',
    'dish',
    'echo',
    'face',
    'game',
    'give',
    'hint',
    'jump',
    'kind',
    'lame',
    'live',
    'load',
    'mail',
    'mind',
    'name',
    'note',
    'nose',
    'oath',
    'pace',
    'park',
    'part',
    'pink',
    'port',
    'pray',
    'rave',
    'read',
    'ride',
    'sale',
  ],
  5: [
    'apple',
    'basic',
    'bible',
    'blade',
    'bless',
    'braid',
    'break',
    'bribe',
    'broke',
    'broom',
    'brown',
    'brush',
    'build',
    'burst',
    'cache',
    'calla',
    'camps',
    'cards',
    'cared',
    'cargo',
    'catch',
    'cause',
    'chain',
    'chair',
    'chart',
    'chase',
    'cheap',
    'check',
    'cheat',
    'chief',
  ],
  6: [
    'castle',
    'cloudy',
    'coffee',
    'column',
    'combat',
    'comedy',
    'common',
    'comply',
    'corner',
    'cosmic',
    'course',
    'cousin',
    'cradle',
    'create',
    'credit',
    'crisis',
    'custom',
    'damage',
    'danger',
    'dealer',
    'debate',
    'decade',
    'decent',
    'decide',
    'defeat',
    'defend',
    'define',
    'degree',
    'delete',
    'demand',
  ],
  7: [
    'ability',
    'absence',
    'academy',
    'account',
    'achieve',
    'address',
    'advance',
    'battery',
    'benefit',
    'cabinet',
    'capital',
    'captain',
    'capture',
    'century',
    'ceramic',
    'certain',
    'chapter',
    'circuit',
    'citizen',
    'climate',
    'clothes',
    'cocaine',
    'college',
    'combine',
    'comfort',
    'command',
    'comment',
    'compact',
    'company',
    'compare',
  ],
  8: [
    'absolute',
    'abstract',
    'academic',
    'accessed',
    'accident',
    'accuracy',
    'accurate',
    'achieved',
    'activity',
    'addition',
    'adequate',
    'adjacent',
    'advanced',
    'advocate',
    'affected',
    'affinity',
    'aircraft',
    'alliance',
    'although',
    'analysis',
    'ancestor',
    'animated',
    'announce',
    'answered',
    'anywhere',
    'apparent',
    'appetite',
    'approval',
    'approach',
    'argument',
  ],
};

export default function NewGame() {
  const [params] = useSearchParams();

  const wordLength = Number(params.get('wordlength')) || 5;

  const [winWord] = useState(() => {
    const arr = WordMap[wordLength];
    const index = randomNo(0, arr.length - 1);
    return arr[index].toUpperCase();
  });
  const [maxGuesses] = useState<number>(() => randomNo(4, 6));

  return (
    <Game winWord={winWord} wordLength={wordLength} maxGuesses={maxGuesses} />
  );
}
